import {useEffect,useState} from 'react';
import Layout from '../components/Layout';
import api from '../api/axios';
import {cacheGet,cacheSet,queueAction} from '../utils/offline';
import {hasRole, ROLES} from '../utils/auth';

export default function Incumplimientos(){
  const [rep,setRep]=useState(cacheGet('incumplimientos')); const [ent,setEnt]=useState([]); const [msg,setMsg]=useState(''); const [f,setF]=useState({entrega_id:'',tipo:'No presentación',descripcion:''});
  async function cargar(){try{setEnt((await api.get('/entregas')).data); const r=await api.get('/incumplimientos'); setRep(r.data); cacheSet('incumplimientos',r.data)}catch{setMsg('Modo offline activo.')}} useEffect(()=>{cargar()},[]);
  async function crear(e){e.preventDefault(); const data={entrega_id:f.entrega_id,descripcion:`${f.tipo}: ${f.descripcion}`}; try{await api.post('/incumplimientos',data); setMsg('✅ Reporte enviado a revisión de la asociación.'); cargar()}catch(err){if(!navigator.onLine){queueAction({url:'/incumplimientos',method:'post',data}); setMsg('🟠 Reporte guardado para sincronizar.')}else setMsg(err.response?.data?.mensaje||'No se pudo registrar el reporte')}}
  async function revisar(id,aprobado){try{await api.put(`/incumplimientos/${id}/revisar`,{aprobado}); setMsg(aprobado?'✅ Reporte aprobado y reputación actualizada':'✅ Reporte rechazado'); cargar()}catch(e){setMsg(e.response?.data?.mensaje||'No se pudo revisar')}}
  return <Layout title='Auditoría e incumplimientos' subtitle={hasRole(ROLES.ADMIN)?'Revisión formal por la asociación':'Reportes relacionados con mis entregas'} color='gris-bg'>{!hasRole(ROLES.ADMIN)&&<form className='form-card' onSubmit={crear}><select required value={f.entrega_id} onChange={e=>setF({...f,entrega_id:e.target.value})}><option value=''>Entrega relacionada</option>{ent.map(e=><option key={e.id} value={e.id}>#{e.id} {e.producto} - {e.fecha_entrega}</option>)}</select><select value={f.tipo} onChange={e=>setF({...f,tipo:e.target.value})}><option>No presentación</option><option>Cantidad no entregada</option><option>Cancelación no avisada</option><option>Otro problema</option></select><textarea required placeholder='Explica el problema con palabras simples' value={f.descripcion} onChange={e=>setF({...f,descripcion:e.target.value})}/><button>⚠️ Reportar incumplimiento</button></form>}<div className='catalogo-grid'>{rep.map(r=><div className='card' key={r.id}><h2>⚠️ Reporte #{r.id}</h2><p>{r.descripcion}</p><p><b>Producto:</b> {r.producto}</p><p><b>Productor:</b> {r.productor}</p><p><b>Comprador:</b> {r.comprador}</p><p>Reportado por: {r.reportado_por}</p><span className='badge'>{r.estado} {r.aprobado?'· APROBADO':''}</span>{hasRole(ROLES.ADMIN)&&r.estado==='PENDIENTE'&&<><button onClick={()=>revisar(r.id,true)}>✅ Aprobar</button><button className='btn-danger' onClick={()=>revisar(r.id,false)}>❌ Rechazar</button></>}</div>)}</div>{msg&&<div className='mensaje'>{msg}</div>}</Layout>
}
